export const shopActionTypes = {
  FETCH_COLLECTIONS_START: "UPDATE_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "UPDATE_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "UPDATE_COLLECTIONS_FAILURE",
};
